# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [ ]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [28]:
# одномерный массив размера 10
z = np.zeros(10)
print(f"{z}\n")

# пятый элемент равен 1
np.put(z, 4, 1)
print(f"{z}\n")

# Трансформируем в двумерный массив
z = z.reshape(2, -1)
print(f"{z}\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]



### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [27]:
# одномерный массив со значениями от 10 до 49
a = np.arange(10, 50)
print(f"{a}\n")

# развернем его (первый элемент становится последним)
a = a[::-1]
print(f"{a}\n")

# Находим в нем все четные элементы.
a = a[a % 2 == 0]
print(f"{a}\n")

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]

[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]



### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [24]:
# 
a = np.arange(0, 9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [26]:
#  массив 4x3x2 со случайными значениями
a = np.random.rand(24).reshape(4, 3, 2)
print(f"{a}\n")

# Находим его минимум и максимум
print("Минимум:", a.min())
print("Максимум:", a.max())

[[[0.38642212 0.28580149]
  [0.25896232 0.58382685]
  [0.13002272 0.93420671]]

 [[0.60991436 0.79695899]
  [0.13096104 0.59829304]
  [0.04483007 0.02050046]]

 [[0.34427032 0.54250235]
  [0.03711735 0.46904084]
  [0.37868128 0.03136217]]

 [[0.82561608 0.76400681]
  [0.0405526  0.75206557]
  [0.74549867 0.43763563]]]

Минимум: 0.020500460406081666
Максимум: 0.9342067114333605


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [32]:
# два двумерных массива размерами 6x4 и 4x3
a = np.random.rand(24).reshape(6, 4)
b = np.random.rand(12).reshape(4, 3)

print(f"{a}\n")
print(f"{b}\n")

# Находим их матричное произведение #1 (метод dot)
c = np.dot(a, b)
print(f"{c}\n")

# Находим их матричное произведение #2 (оператор @)
c = a @ b
print(f"{c}\n")

[[0.072936   0.97797503 0.95942727 0.65759991]
 [0.13181717 0.68250203 0.25903217 0.98295393]
 [0.79213134 0.70665911 0.18934828 0.01419526]
 [0.10863066 0.50335639 0.41195325 0.30927035]
 [0.48360632 0.65751904 0.36369646 0.425317  ]
 [0.96125308 0.49829695 0.69419189 0.64698062]]

[[0.91076687 0.46648709 0.29136379]
 [0.3160803  0.47056273 0.47705269]
 [0.28874589 0.5410829  0.01096107]
 [0.21467573 0.94480665 0.34344209]]

[[0.79374775 1.63465676 0.72416036]
 [0.62159098 1.45151032 0.7044232 ]
 [1.00252891 0.81791137 0.57486272]
 [0.44338089 0.8026371  0.38251046]
 [0.84460253 1.13363233 0.60463485]
 [1.3723154  1.66977907 0.7475977 ]]

[[0.79374775 1.63465676 0.72416036]
 [0.62159098 1.45151032 0.7044232 ]
 [1.00252891 0.81791137 0.57486272]
 [0.44338089 0.8026371  0.38251046]
 [0.84460253 1.13363233 0.60463485]
 [1.3723154  1.66977907 0.7475977 ]]



### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [39]:
# Создаём случайный двумерный массив 7x7
a = np.random.randint(0, 49, size=(7, 7))
print(f"{a}\n")

# Находим у него среднее значение и стандартное отклонение
mean = np.mean(a)
std = np.std(a)
print(f"Среднее значение: {mean}\nСтандартное отклонение: {std}")

[[12  9 32 37  6 33  7]
 [16 37  2 13 34 24 24]
 [ 7 47 33  3  3  3  1]
 [26 35 44  5 20 24 43]
 [33 11 10 36 11 15 44]
 [23 18 20 11  8 25 35]
 [13  8 35 42  2 29 12]]

Среднее значение: 20.836734693877553
Стандартное отклонение: 13.607241377634354


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Загрузите датасет Tips из набора датасетов seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на первые 5 строчек

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте сколько всего строчек и колонок в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Проверьте есть ли пропуски в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на распределение числовых признаков

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите максимальное значение 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите количество курящих людей

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
# ВАШ КОД ЗДЕСЬ

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ